sudo: false
language: python
# Should be identical to envlist in tox.ini. See:
# http://tox.readthedocs.org/en/latest/config.html#confval-envlist=CSV
env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
install:
  pip install coveralls tox
script:
  tox
after_success:
  coveralls
notifications:
    email:
        on_success: always
        on_failure: always
